name: Vercel Preview Deployment
env:
  VERCEL_PROJECT_ID: prj_TDVnVIcvMkqKY3Kwl7qD2sjk8xkB
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=48PtwIo6wwKxkzqmJ6cbasam
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=48PtwIo6wwKxkzqmJ6cbasam
